

rename_dictionary = {
    'State FIPS Code' : 'FIPS_state', 
    'County FIPS Code' : 'FIPS_county',
    '5-digit FIPS Code': 'FIPS_full',
    'State Abbreviation' : 'state', 
    'Name': 'county',
    'Release Year' : 'year',
    'Premature death raw value' : 'YPLL', 
    'Poor or fair health raw value' : 'poor_health',
    'Poor physical health days raw value': 'poor_physical_health_days',
    'Poor mental health days raw value': 'poor_mental_health_days', 
    'Low birthweight raw value' : 'LBW',
    'Adult smoking raw value': 'smokers', 
    'Adult obesity raw value' : 'obese' ,
    'Food environment index raw value' : 'food_environment_index', 
    'Physical inactivity raw value' : 'physically_inactive',
    'Access to exercise opportunities raw value' : 'exercise_acces',
    'Excessive drinking raw value' : 'excessive_drinking',
    'Alcohol-impaired driving deaths raw value' : 'alcohol_impaired_driving_deaths',
    'Sexually transmitted infections raw value' : 'chlamydia_rate', 
    'Teen births raw value' : 'teen_birth_rate',
    'Uninsured raw value' : 'uninsured', 
    'Primary care physicians raw value': 'PCP',
    'Dentists raw value': 'dentists', 
    'Mental health providers raw value' : 'MHP',
    'Preventable hospital stays raw value': 'preventable_hospital_stays',
    'Mammography screening raw value' : 'mammography_screenings', 
    'Flu vaccinations raw value' : 'flu_vaccinated',
    'High school graduation raw value' : 'high_school_graduation', 
    'Some college raw value' : 'college',
    'Unemployment raw value' : 'unemployment', 
    'Children in poverty raw value' : 'children_in_oiverty',
    'Income inequality raw value' : 'income_inequality',
    'Children in single-parent households raw value' : 'children_in_singleparent_household',
    'Social associations raw value' : 'social_associations', 
    'Violent crime raw value' : 'violent_crime',
    'Injury deaths raw value' : 'injury_deaths',
    'Air pollution - particulate matter raw value' : 'air_pollution',
    'Drinking water violations raw value' : 'water_violation',
    'Severe housing problems raw value': 'severe_housing_problems', 
    'Driving alone to work raw value' : 'driving_alone_work',
    'Long commute - driving alone raw value': 'driving_alone_longcommute', 
    'Life expectancy raw value' : 'life_expectancy',
    'Premature age-adjusted mortality raw value' : 'premature_age_adjusted_mortality',
    'Frequent physical distress raw value' : 'frequent_physical_distress',
    'Frequent mental distress raw value' : 'frequent_mental_distress', 
    'Diabetes prevalence raw value' : 'diabetes',
    'Food insecurity raw value' : 'food_insecurity',
    'Limited access to healthy foods raw value' : 'healthy_food_acces',
    'Insufficient sleep raw value': 'insufficient_sleep', 
    'Uninsured adults raw value': 'uninsured_adults',
    'Uninsured children raw value' : 'uninsured_children',
    'Other primary care providers raw value' : 'other_primary_care_providers',
    'Median household income raw value' : 'median_household_income',
    'Children eligible for free or reduced price lunch raw value' : 'children_elig_lunch',
    'Homeownership raw value' : 'homeownership', 
    'Severe housing cost burden raw value' : 'severe_housing_cost_burden',
    'Population raw value' : 'population', 
    '% below 18 years of age raw value' : 'below_age18',
    '% 65 and older raw value' : 'above_age65', 
    '% Non-Hispanic African American raw value' : 'nonhisp_africanamerican',
    '% American Indian and Alaskan Native raw value' : 'americanindian_alaskannative', 
    '% Asian raw value' : 'asian',
    '% Native Hawaiian/Other Pacific Islander raw value' : 'nativehawaiian_otherpacific',
    '% Hispanic raw value' : 'hispanic', 
    '% Non-Hispanic white raw value' : 'nonhispanic_whit',
    '% not proficient in English raw value' : 'notproficient_english', 
    '% Females raw value' : 'females',
    '% Rural raw value' : 'rural'
}